# Generated by Django 5.2 on 2025-05-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('inventario', '0001_initial'),
        ('vehiculo', '0002_alter_m_vehiculo_options_remove_m_vehiculo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción del servicio')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo del servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='m_orden_trabajo',
            fields=[
                ('id_orden', models.AutoField(db_column='id_orden', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico inicial')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('T', 'Terminado'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado de la orden')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.m_vehiculo', verbose_name='Vehículo')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.m_empleado', verbose_name='Mecánico asignado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.m_servicio', verbose_name='Servicio solicitado')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'db_table': 'ordenes_trabajo',
            },
        ),
        migrations.CreateModel(
            name='m_refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.m_orden_trabajo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.m_inventario', verbose_name='Refacción utilizada')),
            ],
            options={
                'verbose_name': 'Detalle de refacción',
                'verbose_name_plural': 'Detalles de refacciones',
                'db_table': 'detalle_refacciones',
            },
        ),
    ]
