# Generated by Django 5.2 on 2025-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_servicio',
            name='servicio',
            field=models.CharField(max_length=250, null=True, verbose_name='Nombre del servicio servicio'),
        ),
    ]
