# Generated by Django 5.2 on 2025-05-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_m_servicio_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_orden_trabajo',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
        migrations.RemoveField(
            model_name='m_orden_trabajo',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='m_refaccion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones', to='ordenes.m_orden_trabajo'),
        ),
        migrations.AlterField(
            model_name='m_servicio',
            name='servicio',
            field=models.CharField(max_length=250, null=True, verbose_name='Nombre del servicio'),
        ),
        migrations.CreateModel(
            name='DetalleServicioOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asociados', to='ordenes.m_orden_trabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.m_servicio')),
            ],
        ),
    ]
