# Generated by Django 5.2 on 2025-05-31 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_detalleservicio_delete_detalleservicioorden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleservicio',
            options={'verbose_name': 'Detalle de Servicio', 'verbose_name_plural': 'Detalles de los servicios'},
        ),
        migrations.AlterModelTable(
            name='detalleservicio',
            table='detalle_servicio',
        ),
    ]
