# Generated by Django 5.2 on 2025-05-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_detalleservicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_orden_trabajo',
            name='entrega_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AlterField(
            model_name='m_orden_trabajo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
