# Generated by Django 5.2 on 2025-06-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('ordenes', '0006_alter_m_orden_trabajo_entrega_estimada_and_more'),
        ('vehiculo', '0004_alter_m_vehiculo_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='m_orden_trabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['P', 'E'])), fields=('id_vehiculo',), name='unique_orden_activa_vehiculo'),
        ),
    ]
