# Generated by Django 5.2 on 2025-06-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_m_orden_trabajo_unique_orden_vehiculo_dia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_orden_trabajo',
            options={'permissions': [('iniciar_orden', 'Puede iniciar orden')], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
    ]
