# Generated by Django 5.2 on 2025-06-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_inventario',
            name='nombre_p',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Producto'),
        ),
    ]
