# Generated by Django 5.2 on 2025-05-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_alter_m_cliente_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='cliente.m_cliente')),
            ],
        ),
    ]
