# Generated by Django 5.2 on 2025-05-22 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_m_cliente_sexo'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.RemoveField(
            model_name='m_vehiculo',
            name='id',
        ),
        migrations.AddField(
            model_name='m_vehiculo',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Creación'),
        ),
        migrations.AddField(
            model_name='m_vehiculo',
            name='id_vehiculo',
            field=models.AutoField(db_column='id_vehiculo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='anio',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='cliente.m_cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='placas',
            field=models.CharField(max_length=20, unique=True, verbose_name='Placas'),
        ),
        migrations.AlterModelTable(
            name='m_vehiculo',
            table='vehiculo',
        ),
    ]
