# Generated by Django 5.2 on 2025-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_m_vehiculo_options_remove_m_vehiculo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(null=True, verbose_name='Kilometraje'),
        ),
        migrations.AddField(
            model_name='m_vehiculo',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='m_vehiculo',
            name='transmision',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('Manual', 'Manual'), ('Automatica', 'Automática')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='anio',
            field=models.PositiveIntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='marca',
            field=models.CharField(max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='m_vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, null=True, verbose_name='Modelo'),
        ),
    ]
