# Generated by Django 5.2 on 2025-04-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
