# Generated by Django 5.2 on 2025-04-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_cliente',
            options={'verbose_name': 'Maestro', 'verbose_name_plural': 'Maestros'},
        ),
        migrations.AddField(
            model_name='m_cliente',
            name='ap_01',
            field=models.CharField(max_length=250, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='m_cliente',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Creacion'),
        ),
        migrations.AlterField(
            model_name='m_cliente',
            name='nombre',
            field=models.CharField(max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterModelTable(
            name='m_cliente',
            table='maestro',
        ),
    ]
