# Generated by Django 5.2 on 2025-04-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_m_cliente_options_m_cliente_ap_01_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelTable(
            name='m_cliente',
            table='cliente',
        ),
    ]
