# Generated by Django 5.2 on 2025-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_m_cliente_direccion_m_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_cliente',
            name='ap_01',
            field=models.CharField(max_length=250, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='m_cliente',
            name='direccion',
            field=models.CharField(max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='m_cliente',
            name='nombre',
            field=models.CharField(max_length=250, null=True, verbose_name='Nombre(s)'),
        ),
    ]
