# Generated by Django 5.2 on 2025-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_m_cliente_sexo_alter_m_cliente_ap_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cliente',
            name='sexo',
            field=models.CharField(choices=[('', 'Selecciona'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
