# Generated by Django 5.2 on 2025-05-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_m_cliente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cliente',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
