# Generated by Django 5.2 on 2025-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_m_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cliente',
            name='sexo',
            field=models.CharField(choices=[('', 'Selecciona una opción'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
