# Generated by Django 5.2 on 2025-06-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_m_cliente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cliente',
            name='email',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Email'),
        ),
    ]
