# Generated by Django 5.2 on 2025-05-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='m_empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, null=True, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=250, null=True, verbose_name='Apellidos')),
                ('sexo', models.CharField(choices=[('', 'Selecciona'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('correo', models.EmailField(max_length=250, null=True, verbose_name='Correo Electrónico')),
                ('contrasenia', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_created', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de creación')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.m_rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
    ]
